version: '1'

app:
  name: pivot
  container: pivot-app
  image: pivot-app:latest
  port: 4004
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - NODE_ENV=production
      - VITE_DISABLE_SOURCEMAP=true
      - COMPOSER_NO_DEV=1
      - NODE_OPTIONS=--max-old-space-size=1536
  env:
    - APP_ENV=production
    - APP_DEBUG=false
  volumes:
    - /var/www/html/pivot/storage:/var/www/storage
    - /var/www/html/pivot/public/images:/var/www/public/images
    - /var/www/html/pivot/.env:/var/www/.env
  remote:
    host: guillaume-lcte.fr
    user: ubuntu
    port: 22
  resources:
    limits:
      memory: 2G
      cpus: '1.0'
  pre_deploy:
    - mkdir -p /var/www/html/pivot/storage/app/public
    - mkdir -p /var/www/html/pivot/storage/framework/cache
    - mkdir -p /var/www/html/pivot/storage/framework/sessions
    - mkdir -p /var/www/html/pivot/storage/framework/views
    - mkdir -p /var/www/html/pivot/storage/logs
    - mkdir -p /var/www/html/pivot/public/images
    - touch /var/www/html/pivot/.env
    - chmod +x docker/pre-build.sh
    - chmod +x docker/post-build.sh
    - ./docker/pre-build.sh
  post_deploy:
    - docker stop pivot-app 2>/dev/null || true
    - docker rm pivot-app 2>/dev/null || true
    - docker run -d --name pivot-app -p 4004:4004 --memory=2g --cpus=1.0 -v /var/www/html/pivot/storage:/var/www/storage -v /var/www/html/pivot/public/images:/var/www/public/images -v /var/www/html/pivot/.env:/var/www/.env --restart unless-stopped pivot-app:latest
    - ./docker/post-build.sh
    - echo "Déploiement terminé avec succès! L'application est accessible sur http://guillaume-lcte.fr:4004" 