version: '1'

app:
  name: pivot
  container: pivot-app
  image: pivot-app:latest
  port: 4004
  build:
    context: .
    dockerfile: Dockerfile
    target: pivot-app
  env:
    - APP_ENV=production
    - APP_DEBUG=false
  remote:
    host: guillaume-lcte.fr
    user: ubuntu
    port: 22  # Port SSH standard, changez-le si différent 