php:
  preset: laravel
  version: 8.2
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
    exclude:
      - "modules"
      - "node_modules"
      - "nova"
      - "nova-components"
      - "storage"
      - "vendor"
    name:
      - "*.php"
    not-name:
      - "*.blade.php"
      - "_ide_helper.php" 