FROM php:8.2-fpm AS base

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libicu-dev \
    zip \
    unzip \
    nginx \
    supervisor \
    procps \
    iputils-ping \
    net-tools \
    dnsutils \
    telnet \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure intl \
    && docker-php-ext-install -j$(nproc) \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    zip \
    mysqli \
    intl

# Get Composer
COPY --from=composer:2.6.5 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Prepare directory structure
RUN mkdir -p /var/www/storage/app/public \
    /var/www/storage/framework/cache \
    /var/www/storage/framework/sessions \
    /var/www/storage/framework/views \
    /tmp/laravel-logs \
    /var/www/bootstrap/cache \
    /var/www/public/images \
    /var/www/public/build \
    /var/www/public/build/assets/js \
    /var/www/public/build/assets/css \
    /var/www/public/assets/js \
    /var/www/public/assets/css \
    /var/www/docker \
    /var/www/resources/views/components

# Copy configuration files
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/entrypoint.sh /var/www/docker/entrypoint.sh
RUN chmod +x /var/www/docker/entrypoint.sh

# Create diagnostic files
RUN echo '<?php phpinfo();' > /var/www/public/info.php \
    && echo '<?php echo json_encode(["status" => "ok", "timestamp" => time()]);' > /var/www/public/health-check.php

# Create a script to handle assets in production
RUN echo "<?php" > /var/www/public/fix-assets.php && \
    echo " " >> /var/www/public/fix-assets.php && \
    echo "/**" >> /var/www/public/fix-assets.php && \
    echo " * Script d'urgence pour gérer les assets manquants en production" >> /var/www/public/fix-assets.php && \
    echo " */" >> /var/www/public/fix-assets.php && \
    echo " " >> /var/www/public/fix-assets.php && \
    echo "// Liste des fichiers demandés fréquemment" >> /var/www/public/fix-assets.php && \
    echo "\$requestedFiles = [" >> /var/www/public/fix-assets.php && \
    echo "    \"build/assets/css/app-CjAB3oxN.css\"," >> /var/www/public/fix-assets.php && \
    echo "    \"build/assets/js/vendor-CLLTD4I8.js\"," >> /var/www/public/fix-assets.php && \
    echo "    \"build/assets/js/app-gZAm2HJZ.js\"" >> /var/www/public/fix-assets.php && \
    echo "];" >> /var/www/public/fix-assets.php && \
    echo " " >> /var/www/public/fix-assets.php && \
    echo "// Créer les répertoires et fichiers si nécessaire" >> /var/www/public/fix-assets.php && \
    echo "foreach (\$requestedFiles as \$file) {" >> /var/www/public/fix-assets.php && \
    echo "    \$fullPath = __DIR__ . \"/\" . \$file;" >> /var/www/public/fix-assets.php && \
    echo "    \$dir = dirname(\$fullPath);" >> /var/www/public/fix-assets.php && \
    echo "    " >> /var/www/public/fix-assets.php && \
    echo "    if (!is_dir(\$dir)) {" >> /var/www/public/fix-assets.php && \
    echo "        mkdir(\$dir, 0755, true);" >> /var/www/public/fix-assets.php && \
    echo "    }" >> /var/www/public/fix-assets.php && \
    echo "    " >> /var/www/public/fix-assets.php && \
    echo "    if (!file_exists(\$fullPath)) {" >> /var/www/public/fix-assets.php && \
    echo "        if (strpos(\$file, \".js\") !== false) {" >> /var/www/public/fix-assets.php && \
    echo "            file_put_contents(\$fullPath, \"console.log(\\\"Fallback asset generated by Docker\\\");\");" >> /var/www/public/fix-assets.php && \
    echo "        } else {" >> /var/www/public/fix-assets.php && \
    echo "            file_put_contents(\$fullPath, \"/* Fallback asset generated by Docker */\");" >> /var/www/public/fix-assets.php && \
    echo "        }" >> /var/www/public/fix-assets.php && \
    echo "    }" >> /var/www/public/fix-assets.php && \
    echo "}" >> /var/www/public/fix-assets.php && \
    echo " " >> /var/www/public/fix-assets.php && \
    echo "// Créer manifest.json si nécessaire" >> /var/www/public/fix-assets.php && \
    echo "\$manifestPath = __DIR__ . \"/build/manifest.json\";" >> /var/www/public/fix-assets.php && \
    echo "if (!file_exists(\$manifestPath)) {" >> /var/www/public/fix-assets.php && \
    echo "    \$manifest = [" >> /var/www/public/fix-assets.php && \
    echo "        \"resources/js/app.jsx\" => [" >> /var/www/public/fix-assets.php && \
    echo "            \"file\" => \"js/app-gZAm2HJZ.js\"," >> /var/www/public/fix-assets.php && \
    echo "            \"isEntry\" => true," >> /var/www/public/fix-assets.php && \
    echo "            \"src\" => \"resources/js/app.jsx\"" >> /var/www/public/fix-assets.php && \
    echo "        ]," >> /var/www/public/fix-assets.php && \
    echo "        \"resources/css/app.css\" => [" >> /var/www/public/fix-assets.php && \
    echo "            \"file\" => \"css/app-CjAB3oxN.css\"," >> /var/www/public/fix-assets.php && \
    echo "            \"isEntry\" => true," >> /var/www/public/fix-assets.php && \
    echo "            \"src\" => \"resources/css/app.css\"" >> /var/www/public/fix-assets.php && \
    echo "        ]" >> /var/www/public/fix-assets.php && \
    echo "    ];" >> /var/www/public/fix-assets.php && \
    echo "    file_put_contents(\$manifestPath, json_encode(\$manifest, JSON_PRETTY_PRINT));" >> /var/www/public/fix-assets.php && \
    echo "}" >> /var/www/public/fix-assets.php && \
    echo " " >> /var/www/public/fix-assets.php && \
    echo "echo \"Assets check completed successfully\";" >> /var/www/public/fix-assets.php

# Copy dependencies first for better caching
COPY composer.json composer.lock ./
COPY package.json package-lock.json ./

# Install PHP dependencies
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install \
    --no-autoloader \
    --no-scripts \
    --no-dev \
    --no-interaction \
    --prefer-dist

# Install Node.js dependencies and build assets
RUN npm ci && npm run build

# Copy application code
COPY --chown=www-data:www-data . .

# Configure logs
RUN rm -rf /var/www/storage/logs && \
    ln -sf /tmp/laravel-logs /var/www/storage/logs

# Copy environment file
COPY docker/env.production /var/www/.env

# Create fallback assets in case they are missing
RUN mkdir -p /var/www/public/build/assets/js \
    /var/www/public/build/assets/css \
    /var/www/public/assets/js \
    /var/www/public/assets/css && \
    echo "console.log('Fallback app bundle');" > /var/www/public/build/assets/js/app-gZAm2HJZ.js && \
    echo "console.log('Fallback vendor bundle');" > /var/www/public/build/assets/js/vendor-CLLTD4I8.js && \
    echo "/* Fallback CSS */" > /var/www/public/build/assets/css/app-CjAB3oxN.css && \
    cp /var/www/public/build/assets/js/app-gZAm2HJZ.js /var/www/public/assets/js/ && \
    cp /var/www/public/build/assets/js/vendor-CLLTD4I8.js /var/www/public/assets/js/ && \
    cp /var/www/public/build/assets/css/app-CjAB3oxN.css /var/www/public/assets/css/

# Create manifest.json if it doesn't exist from the build
RUN if [ ! -f /var/www/public/build/manifest.json ]; then \
    echo '{ \
        "resources/js/app.jsx": { \
            "file": "js/app-gZAm2HJZ.js", \
            "isEntry": true, \
            "src": "resources/js/app.jsx" \
        }, \
        "resources/css/app.css": { \
            "file": "css/app-CjAB3oxN.css", \
            "isEntry": true, \
            "src": "resources/css/app.css" \
        } \
    }' > /var/www/public/build/manifest.json; \
    fi

# Copy the manifest to the assets directory as well
RUN cp -f /var/www/public/build/manifest.json /var/www/public/assets/manifest.json

# Set permissions
RUN chmod -R 777 /var/www/storage \
    && chmod -R 777 /var/www/bootstrap/cache \
    && chmod -R 777 /tmp/laravel-logs \
    && chmod -R 777 /var/www/public/build \
    && chmod -R 777 /var/www/public/assets \
    && chown -R www-data:www-data /var/www \
    && chown -R www-data:www-data /tmp/laravel-logs \
    && touch /tmp/laravel-logs/laravel.log \
    && chmod 666 /tmp/laravel-logs/laravel.log

# Generate optimized autoloader
RUN COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload --no-dev --optimize

# Install Breeze for Blade components
RUN COMPOSER_ALLOW_SUPERUSER=1 composer require --no-interaction laravel/breeze

# Create Blade components manually
RUN echo '<label {{ $attributes->merge(["class" => "block font-medium text-sm text-gray-700"]) }}>{{ $slot }}</label>' > /var/www/resources/views/components/input-label.blade.php && \
    echo '<input {{ $attributes->merge(["class" => "border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"]) }}>' > /var/www/resources/views/components/text-input.blade.php && \
    echo '<input type="checkbox" {!! $attributes->merge(["class" => "rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500"]) !!}>' > /var/www/resources/views/components/checkbox.blade.php && \
    echo '<button {{ $attributes->merge(["type" => "submit", "class" => "inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 focus:bg-gray-700 active:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150"]) }}>{{ $slot }}</button>' > /var/www/resources/views/components/primary-button.blade.php && \
    echo '<div {{ $attributes->merge(["class" => "text-sm text-red-600 space-y-1"]) }}>{{ $slot }}</div>' > /var/www/resources/views/components/input-error.blade.php && \
    echo '<div {{ $attributes->merge(["class" => "p-4 text-sm text-gray-600"]) }}>{{ $slot }}</div>' > /var/www/resources/views/components/auth-session-status.blade.php

# Cleanup
RUN rm -rf /var/www/node_modules \
    /var/www/.git \
    /var/www/.github \
    && find /var/www -name ".git*" -type f -delete \
    && composer clear-cache

# Expose port
EXPOSE 4004

# Run entrypoint
ENTRYPOINT ["/var/www/docker/entrypoint.sh"] 