version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20
        - PORT=4004
        - UID=1000
        - GID=1000
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "4004:4004"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true  # Temporairement à true pour le debug
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - PHP_MEMORY_LIMIT=512M
      - NODE_OPTIONS=--max-old-space-size=4096
      - DISABLE_JIT=true  # Désactive explicitement JIT pour OPCache
    volumes:
      - ./storage/app/public:/var/www/storage/app/public
      - ./storage/logs:/var/www/storage/logs
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pivot.rule=Host(`pivot.guillaume-lcte.fr`)"
      - "traefik.http.routers.pivot.entrypoints=web,websecure"
      - "traefik.http.routers.pivot.tls.certresolver=letsencrypt"
      - "traefik.http.services.pivot.loadbalancer.server.port=4004"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4004"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

networks:
  web:
    external: true  # Assume un réseau 'web' existant pour Traefik 