<?php
/**
 * Script d'urgence pour gérer les assets manquants en production
 */

header('Content-Type: text/plain');
echo "=== Script de correction des assets ===\n\n";

// Liste des fichiers demandés fréquemment
$requestedFiles = [
    "build/assets/js/app-gZAm2HJZ.js",
    "build/assets/js/vendor-CLLTD4I8.js",
    "build/assets/css/app-CjAB3oxN.css",
    "assets/js/app-gZAm2HJZ.js",
    "assets/js/vendor-CLLTD4I8.js",
    "assets/css/app-CjAB3oxN.css"
];

// Créer les répertoires et fichiers si nécessaire
foreach ($requestedFiles as $file) {
    $fullPath = __DIR__ . "/" . $file;
    $dir = dirname($fullPath);
    
    if (!is_dir($dir)) {
        echo "Création du répertoire {$dir}...\n";
        mkdir($dir, 0755, true);
        echo "✅ Répertoire créé.\n";
    }
    
    if (!file_exists($fullPath)) {
        echo "Création du fichier {$file}...\n";
        if (strpos($file, ".js") !== false) {
            $content = "console.log('Fallback asset generated by fix-assets.php');";
        } else {
            $content = "/* Fallback asset generated by fix-assets.php */\n";
            $content .= "body { font-family: system-ui, sans-serif; }\n";
        }
        file_put_contents($fullPath, $content);
        echo "✅ Fichier créé.\n";
    } else {
        echo "Le fichier {$file} existe déjà.\n";
    }
}

// Créer des versions sans hash
$noHashFiles = [
    "build/assets/js/app.js" => "build/assets/js/app-gZAm2HJZ.js",
    "build/assets/js/vendor.js" => "build/assets/js/vendor-CLLTD4I8.js",
    "build/assets/css/app.css" => "build/assets/css/app-CjAB3oxN.css",
    "assets/js/app.js" => "assets/js/app-gZAm2HJZ.js",
    "assets/js/vendor.js" => "assets/js/vendor-CLLTD4I8.js",
    "assets/css/app.css" => "assets/css/app-CjAB3oxN.css"
];

foreach ($noHashFiles as $dest => $src) {
    $fullSrc = __DIR__ . "/" . $src;
    $fullDest = __DIR__ . "/" . $dest;
    
    if (file_exists($fullSrc) && !file_exists($fullDest)) {
        echo "Copie de {$src} vers {$dest}...\n";
        copy($fullSrc, $fullDest);
        echo "✅ Fichier copié.\n";
    } else if (!file_exists($fullDest)) {
        echo "Création du fichier {$dest}...\n";
        if (strpos($dest, ".js") !== false) {
            $content = "console.log('Non-hash fallback generated by fix-assets.php');";
        } else {
            $content = "/* Non-hash fallback generated by fix-assets.php */\n";
        }
        file_put_contents($fullDest, $content);
        echo "✅ Fichier créé.\n";
    }
}

// Créer manifest.json pour build/ et assets/
$manifestDirs = ["build", "assets"];
$manifest = [
    "resources/js/app.jsx" => [
        "file" => "js/app-gZAm2HJZ.js",
        "isEntry" => true,
        "src" => "resources/js/app.jsx"
    ],
    "resources/css/app.css" => [
        "file" => "css/app-CjAB3oxN.css",
        "isEntry" => true,
        "src" => "resources/css/app.css"
    ]
];

foreach ($manifestDirs as $dir) {
    $manifestPath = __DIR__ . "/{$dir}/manifest.json";
    echo "Vérification de manifest.json dans {$dir}/...\n";
    
    if (!file_exists($manifestPath)) {
        echo "Création de manifest.json dans {$dir}/...\n";
        file_put_contents($manifestPath, json_encode($manifest, JSON_PRETTY_PRINT));
        echo "✅ Fichier manifest.json créé.\n";
    } else {
        echo "Le fichier manifest.json existe déjà dans {$dir}/.\n";
    }
}

// Créer des fichiers .htaccess pour la gestion des assets
$htaccessFiles = [
    "build/assets/.htaccess" => <<<EOT
<IfModule mod_headers.c>
    Header set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
    Header set Pragma "no-cache"
    Header set Expires "0"
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # Redirect to assets directory if file not found
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /assets/$1 [L,QSA]
</IfModule>
EOT,
    "assets/.htaccess" => <<<EOT
<IfModule mod_headers.c>
    Header set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
    Header set Pragma "no-cache"
    Header set Expires "0"
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # Redirect to build/assets directory if file not found
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /build/assets/$1 [L,QSA]
</IfModule>
EOT
];

foreach ($htaccessFiles as $file => $content) {
    $fullPath = __DIR__ . "/" . $file;
    $dir = dirname($fullPath);
    
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    
    echo "Vérification du fichier .htaccess dans {$file}...\n";
    if (!file_exists($fullPath)) {
        echo "Création du fichier .htaccess dans {$file}...\n";
        file_put_contents($fullPath, $content);
        echo "✅ Fichier .htaccess créé.\n";
    } else {
        echo "Le fichier .htaccess existe déjà dans {$file}.\n";
    }
}

echo "\n✅ Opération terminée. Rechargez la page principale et vérifiez si les assets se chargent correctement."; 